on:
  pull_request:
  push:
    branches:
    - main
    tags:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/frankh/sendto
        tags: |
          type=semver,pattern={{version}}
          type=sha

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        outputs: type=image
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha,scope=sendto
        cache-to: type=gha,scope=sendto,mode=max